#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC12B8E73B30F2FC8 (infra-root@openstack.org)
#
Name     : osprofiler
Version  : 3.3.0
Release  : 59
URL      : https://tarballs.openstack.org/osprofiler/osprofiler-3.3.0.tar.gz
Source0  : https://tarballs.openstack.org/osprofiler/osprofiler-3.3.0.tar.gz
Source1  : https://tarballs.openstack.org/osprofiler/osprofiler-3.3.0.tar.gz.asc
Summary  : OpenStack Profiler Library
Group    : Development/Tools
License  : Apache-2.0
Requires: osprofiler-bin = %{version}-%{release}
Requires: osprofiler-license = %{version}-%{release}
Requires: osprofiler-python = %{version}-%{release}
Requires: osprofiler-python3 = %{version}-%{release}
Requires: WebOb
Requires: importlib_metadata
Requires: netaddr
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.serialization
Requires: oslo.utils
Requires: requests
Requires: six
BuildRequires : WebOb
BuildRequires : buildreq-distutils3
BuildRequires : netaddr
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : requests
BuildRequires : six

%description
OSProfiler -- Library for cross-project profiling
        ===================================================

%package bin
Summary: bin components for the osprofiler package.
Group: Binaries
Requires: osprofiler-license = %{version}-%{release}

%description bin
bin components for the osprofiler package.


%package license
Summary: license components for the osprofiler package.
Group: Default

%description license
license components for the osprofiler package.


%package python
Summary: python components for the osprofiler package.
Group: Default
Requires: osprofiler-python3 = %{version}-%{release}

%description python
python components for the osprofiler package.


%package python3
Summary: python3 components for the osprofiler package.
Group: Default
Requires: python3-core
Provides: pypi(osprofiler)
Requires: pypi(netaddr)
Requires: pypi(oslo.concurrency)
Requires: pypi(oslo.serialization)
Requires: pypi(oslo.utils)
Requires: pypi(prettytable)
Requires: pypi(requests)
Requires: pypi(six)
Requires: pypi(webob)

%description python3
python3 components for the osprofiler package.


%prep
%setup -q -n osprofiler-3.3.0
cd %{_builddir}/osprofiler-3.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1595516479
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/osprofiler
cp %{_builddir}/osprofiler-3.3.0/LICENSE %{buildroot}/usr/share/package-licenses/osprofiler/172ca3bbafe312a1cf09cfff26953db2f425c28e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/osprofiler

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/osprofiler/172ca3bbafe312a1cf09cfff26953db2f425c28e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
