#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : osprofiler
Version  : 1.4.0
Release  : 32
URL      : http://tarballs.openstack.org/osprofiler/osprofiler-1.4.0.tar.gz
Source0  : http://tarballs.openstack.org/osprofiler/osprofiler-1.4.0.tar.gz
Source99 : http://tarballs.openstack.org/osprofiler/osprofiler-1.4.0.tar.gz.asc
Summary  : OpenStack Profiler Library
Group    : Development/Tools
License  : Apache-2.0
Requires: osprofiler-bin
Requires: osprofiler-python
Requires: WebOb
Requires: oslo.config
Requires: oslo.messaging
Requires: oslo.utils
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0002-Fix-Exception-when-recursion-limit-is-exceeded.patch

%description
===========================================================
OSProfiler -- Library for cross-project profiling library
===========================================================

%package bin
Summary: bin components for the osprofiler package.
Group: Binaries

%description bin
bin components for the osprofiler package.


%package python
Summary: python components for the osprofiler package.
Group: Default

%description python
python components for the osprofiler package.


%prep
%setup -q -n osprofiler-1.4.0
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489273982
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489273982
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/osprofiler

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
